redcreeper14385/the-code-land

php/BasicOOP.php
We are in Hacktoberfest, and this is my contribution!
=> Basic OOP in php.

python/doubly_linked_list.py, python/requirements.txt, python/singly_linked_lists.py
Added doubly and singly linked list data structures in python with tests and explanations.
If it's ok I can add other data structure implementations that I made when I was studying. It's all covered with tests and can be used both for learning data structures, creation of classes and also building up tests with pytest.
=> Added doubly and singly linked list data structures in python

NodeJs/README.md, NodeJs/helloWorld.js, NodeJs/recursion.js
I added 2 NodeJs code snippets and a readme for NodeJs with explanation.
One code snippet has 2 different ways of displaying the text 'Hello world!' in the console. It explains how to log something in the console, when to use which variable type and the basics of working with an array.
The second code snippet explains how to use recursion, what it can be used for and it has a simple example doing some simple maths.
The readme has been added to have a simple step by step tutorial on how to run a NodeJs application/file.
=> Added NodeJs code snippets with explanation.

python/math_basic_problem.py
Add and multiply program in python
Great for beginners to learn the basics
=> math_basic_problem.py

.vscode/settings.json, python/duplicate_char_counter.py
An expansion of a CodeWars problem, with lots of detailed comments.
=> Added duplicate_char_counter.py

C/hello_world, C/stack_implementation
in this PR i have Introduced a new folder for C language which contains code for classic hello world program and a very easy to understand implementation of stack Data structure in c language, looking forward for feedback's.
thank you!
=> Phagun jain

python/postgres_connection.py, python/redshift_connection.py, python/s3_upload.py
*connect to database and do queries
*upload to s3 bucket.
=> connect to database and upload files to s3 bucket

python/key_of_max_dict_value.py
PR with added "key_of_max_dict_value.py" example. 
Please mark for hacktober on approval :)
=> Key of Max Dictionary Value (Python)

python/send_email/send_email.py, python/send_email/storage_alert.sh
simple script to send storage alert in email.
=> Postgresql

C/Chain Matrix Multiplication.c, java/LAN TicTacToe/ClientT.java, java/LAN TicTacToe/README.md, java/LAN TicTacToe/ServerT.java
I added one dynamic programming algorithm of Chain Matrix Multiplication using C language.
Also I have made a TicTacToe console based LAN gaming, which 2 friends can play if they are connected over same LAN. This code is written in JAVA.
=> Added LAN TicTacToe using java and Chain matrix multiplication using C

python/bubble_sort.py
Example of bubble sort implement in python
=> Bubble sort in python

C/fizzbuzz.c
Just added a basic program like fizzbuzz so that people can learn too.
=> Added fizzbuzz in C

python/dynamic_prog.py
Explained importance of dynamic programming, using the example of Fibonacci Numbers
=> Explain importance of dynamic programming

python/stack_and_queue.py
Code explaining implementation and differences between Stacks and Queues
=> Upload implementation of basic Stacks and Queues

bash/prompt-formatting.sh
I made this simple script to help people start with bash prompt modifications and to get their hands on color coding.
Everything in the script itself is documented to help everyone understand how that works.
Happy Hacktoberfest everyone!
-Dergyitheron
=> Bash prompt formatting script

python/generate_random_pass.py
This is simple random password generator in python using secrets and string module.
=> this is simple password generator

python/aws_rekognition.py
Added an example script that can compare faces using AWS rekognition service, one can use this in various cases and don't need to have their own face compare algorithm.
=> added example script to compare faces using aws rekognition

shell/automate_dms_task.sh
this script runs aws dms task using aws cli 2.
=> this script runs aws dms task

python/get_ip_address.py
simple program in python for getting the client's desktop host name and IP address.
=> IP address of client

php/fizzbuzz.php
My small contribution to php code land. Happy coding :)
=> shortest-fizzbuzz in php

java/programming basics/Strings.java
Add basic implementation of Strings in Java
#Hacktoberfest
=> Add basic implementation of Strings in Java
